@extends('layouts.main')



@section('title', 'Help')



@section('content')

<section class="terms">

    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <h2>Terms&amp;Conditions</h2>

                <p>PLEASE READ THIS DOCUMENT CAREFULLY BEFORE USING ANY SWURV, LLC PRODUCT. THIS DOCUMENT PROVIDES IMPORTANT INFORMATION CONCERNING THE SQUEALOCK SERVICE (SOFWARE, WEBSITE), PROVIDES YOU WITH A LICENSE TO USE OUR SERVICES “AS IS” AND AGREEING TO BE BOUND BY THE TERMS OF THIS AGREEMENT, AND SWURV, LLC’S PRIVACY POLICY WHICH CAN ALSO BE FOUND ON THIS PAGE. IN NO EVENT WILL THE AUTHORS BE HELD LIABLE FOR ANY DAMAGES ARISING FROM THE USE OF THE SQUEALOCK SERVICE. IF YOU DO NOT WISH TO DO SO, DO NOT USE THE SERVICE. This is an agreement between Swurv, LLC, a Washington State corporation, the owner and operator of www.squealock.com (the "Squealock Site"), the Squealock software, including Squealock anti-theft, Squealock Messenger, and Squealock, including all content provided by Swurv, LLC through our services (software and website) and any user of the Squealock Service (Squealock site, Squealock Messenger, and Squealock Crypto).
                    Intellectual Property
                    The design of Squealock applications along with created text, sounds, scripts, graphics, and animations, and the trademarks, service marks and logos contained therein ("Marks"), are owned by or licensed to Swurv, LLC, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. The Service is provided to you AS IS for your information and personal use only. Swurv, LLC reserves all rights not expressly granted in and to the Service. You agree to not engage in the use, copying, or distribution of any of the Service other than expressly permitted herein, including any use, copying, or distribution of Status Submissions of third parties obtained through the Service for any commercial purposes. You further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, through our software (Squealock Messenger & Squealock Crypto) unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Swurv, LLC all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage Swurv, LLC or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business; (v) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (vi) interfere with or disrupt the integrity or performance of the Service or the data contained therein; or (vii) attempt to gain unauthorized access to the Service or its related systems or networks. Swurv, LLC may terminate a user's access to the Service without prior notice and at its sole discretion, if they are determined to be a repeat infringer, or for any or no reason, including being annoying. An annoying person is anyone who is (capriciously or not) determined to be annoying by authorized Swurv, LLC employees.
                    Access to Service
                    Swurv, LLC hereby grants you permission to use the Squealock Service, provided that: (i) your use of the Service as permitted is solely for your personal use, and you are not permitted to resell or charge others for use of or access to the Service, or in any other manner inconsistent with these Terms of Service; (ii) you will not duplicate, transfer, give access to, copy or distribute any part of the Service in any medium without Squealock' s prior written authorization; (iii) you will not attempt to reverse engineer, alter or modify any part of the Service; and (iv) you will otherwise comply with the terms and conditions of these Terms of Service and Privacy Policy. In order to access and use the features of the Service, you acknowledge and agree that you will have to provide Swurv, LLC with your email address. You must notify Swurv, LLC immediately of any breach of security or unauthorized use of your mobile phone. Although Swurv, LLC will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of Swurv, LLC or others due to such unauthorized use. You agree not to use or launch any automated system (for example load testers, robots) that accesses the Service in a manner that sends more request messages to Swurv, LLC servers in a given period of time than a human can reasonably produce in the same period by using a Swurv, LLC application, and you are forbidden from ripping the content unless specifically allowed. Notwithstanding the foregoing, Swurv, LLC grants the operators of public search engines permission to use spiders to copy materials from the website for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. Swurv, LLC reserves the right to revoke these exceptions either generally or in specific cases. We do not condone any efforts to reverse-engineer our system, our protocols, or explore outside the boundaries of the normal requests made by Squealock applications. We have to disallow using request modification tools such as fiddler or whisker, or the like or any other such tools activities that are meant to explore or harm, penetrate or test the site. You must secure our permission before you measure, test, health check or otherwise monitor any network equipment, servers or assets hosted on our domain. You agree not to collect or harvest any personally identifiable information from the Service, nor to use the communication systems provided by the Service for any commercial solicitation or spam purposes. You agree not to spam, or solicit for commercial purposes, any users of the Service.
                    Limitation of Liability
                    In no event shall Swurv, LLC, its officers, directors, employees, or agents, be liable to you for any direct, indirect, incidental, special, punitive, or consequential damages whatsoever resulting from any (i) errors, mistakes, or inaccuracies of content, (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our service, (iii) any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, (iv) any interruption or cessation of transmission to or from our servers, (iv) any bugs, viruses, Trojan horses, or the like, which may be transmitted to or through our service by any third party, (v) any errors or omissions in any content or for any loss or damage of any kind incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available via the Swurv, LLC client, whether based on warranty, contract, tort, or any other legal theory, and whether or not the company is advised of the possibility of such damages, and/or (vi) the disclosure of information pursuant to these terms of service or privacy policy. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction. You specifically acknowledge that Swurv, LLC shall not be liable for user submissions or the defamatory, offensive, or illegal conduct of any third party and that the risk of harm or damage from the foregoing rests entirely with you. The Service is controlled and offered by Swurv, LLC from its facilities in the United States of America. Swurv, LLC makes no representations that the Squealock Service is appropriate or available for use in other locations. Those who access or use the Squealock Service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>

                </div>
            </div>



        </div>

    </section>

    @stop